# client-x.yaml
---
# Deploy 'demo-01' Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: demo-01
---
# Deploy 'client-x' Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-x
  namespace: demo-01
---
# Deploy 'client-x' (dummy) Service [Required by OSM]
apiVersion: v1
kind: Service
metadata:
  # The name of the Service must match the name the app label;
  # OSM Bug, see https://github.com/openservicemesh/osm/issues/1524
  name: client-x
  namespace: demo-01
spec:
  selector:
    app: client-x
  ports:
  - protocol: TCP
    port: 9999
    name: dummy-unused-port
---
# Deploy 'client-x' Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-x-deployment
  namespace: demo-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-x
  template:
    metadata:
      labels:
        app: client-x
    spec:
      serviceAccountName: client-x
      containers:
      - name: client-x
        image: patrice1972/client-x:1.0.0
        env:
        - name: API_HOST
          value: "service-a-service.demo-01"
