# service-a.yaml
---
# Deploy 'demo-01' Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: demo-01
---
# Deploy 'service-a' Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
  namespace: demo-01
---
# Deploy 'service-a' Service
apiVersion: v1
kind: Service
metadata:
  # The name of the Service must match the name the app label;
  # OSM Bug, see https://github.com/openservicemesh/osm/issues/1524
  name: service-a
  namespace: demo-01
spec:
  selector:
    app: service-a
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
# Deploy 'service-a' Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
  namespace: demo-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      serviceAccountName: service-a
      containers:
      - name: service-a
        image: patrice1972/service-a:1.0.0
        ports:
        - name: service-a-port
          protocol: TCP
          containerPort: 3000
